[[libtapi]]
arch = "x86_64"
git-tree-sha1 = "9b08fd4d96507b1abc4b2045282aa5fbce9ad847"
libc = "glibc"
os = "linux"

    [[libtapi.download]]
    sha256 = "844323230610513f8b94868b443ac0adb10d7a001ee7e40116ec10331f7f558e"
    url = "https://github.com/staticfloat/libtapi_jll.jl/releases/download/v1300.6.1-GCCBootstrap-x86_64-linux-gnu/libtapi-v1300.6.1-x86_64-linux-gnu.tar.gz"

[[libtapi-build_log]]
arch = "x86_64"
git-tree-sha1 = "83c88da73f79c33e2cba2bc9ecfb09fd9a553e93"
lazy = true
libc = "glibc"
os = "linux"

    [[libtapi-build_log.download]]
    sha256 = "a8e4a129fafcbb476dcdf383eee4db58506ac55e625d31beba3fb6fe8d13f869"
    url = "https://github.com/staticfloat/libtapi_jll.jl/releases/download/v1300.6.1-GCCBootstrap-x86_64-linux-gnu/libtapi-build_log-v1300.6.1-x86_64-linux-gnu.tar.gz"

[[libtapi-extract_log]]
arch = "x86_64"
git-tree-sha1 = "164bfe309f29e89db3b5f6798d3bca44442f4a0d"
lazy = true
libc = "glibc"
os = "linux"

    [[libtapi-extract_log.download]]
    sha256 = "474ab9f540045bf870b7d15f93c5615e676863c262301de51b0c3975b5a4a2d4"
    url = "https://github.com/staticfloat/libtapi_jll.jl/releases/download/v1300.6.1-GCCBootstrap-x86_64-linux-gnu/libtapi-extract_log-v1300.6.1-x86_64-linux-gnu.tar.gz"
