[[libtapi]]
arch = "x86_64"
git-tree-sha1 = "9b08fd4d96507b1abc4b2045282aa5fbce9ad847"
libc = "glibc"
os = "linux"

    [[libtapi.download]]
    sha256 = "1dc7bf80276c7e3f60ca5aa8a72c0852dbcfe3ba3bbb30d004c0716735c84c94"
    url = "https://github.com/staticfloat/libtapi_jll.jl/releases/download/v1300.6.1-GCCBootstrap-x86_64-linux-gnu/libtapi-v1300.6.1-x86_64-linux-gnu.tar.gz"

[[libtapi-build_log]]
arch = "x86_64"
git-tree-sha1 = "192be3d58329253b896ca6b7ea06ccbd0459cea7"
lazy = true
libc = "glibc"
os = "linux"

    [[libtapi-build_log.download]]
    sha256 = "2aeb4ee67da62deda26ecd9d3220e638ed593ea5eee8768d63b073ac2403db53"
    url = "https://github.com/staticfloat/libtapi_jll.jl/releases/download/v1300.6.1-GCCBootstrap-x86_64-linux-gnu/libtapi-build_log-v1300.6.1-x86_64-linux-gnu.tar.gz"

[[libtapi-extract_log]]
arch = "x86_64"
git-tree-sha1 = "47bd3c2f09574abaf723599ac107018633cb6339"
lazy = true
libc = "glibc"
os = "linux"

    [[libtapi-extract_log.download]]
    sha256 = "572d12af6d64b8469992b98e59f8853caadb45e7b24407d0a4c1bb88ca97a6d2"
    url = "https://github.com/staticfloat/libtapi_jll.jl/releases/download/v1300.6.1-GCCBootstrap-x86_64-linux-gnu/libtapi-extract_log-v1300.6.1-x86_64-linux-gnu.tar.gz"
