[[libtapi]]
arch = "x86_64"
git-tree-sha1 = "9b08fd4d96507b1abc4b2045282aa5fbce9ad847"
libc = "glibc"
os = "linux"

    [[libtapi.download]]
    sha256 = "f20736298a2b688bd642566fc2f67f611f0c36b636397a37c2f80a9e8551f16c"
    url = "https://github.com/staticfloat/libtapi_jll.jl/releases/download/v1300.6.1-GCCBootstrap-x86_64-linux-gnu/libtapi-v1300.6.1-x86_64-linux-gnu.tar.gz"

[[libtapi-build_log]]
arch = "x86_64"
git-tree-sha1 = "6e8dd21c9a0b6ad23002ea02a67796270f15ffe3"
lazy = true
libc = "glibc"
os = "linux"

    [[libtapi-build_log.download]]
    sha256 = "4b9281cfe6233fe0ccd8a02dc3c05376c13e3c5eb9aecd9d46f1afe2a3d11dc4"
    url = "https://github.com/staticfloat/libtapi_jll.jl/releases/download/v1300.6.1-GCCBootstrap-x86_64-linux-gnu/libtapi-build_log-v1300.6.1-x86_64-linux-gnu.tar.gz"

[[libtapi-extract_log]]
arch = "x86_64"
git-tree-sha1 = "bc429ba9ebdf9da41c9a05d848eae8f569ab815f"
lazy = true
libc = "glibc"
os = "linux"

    [[libtapi-extract_log.download]]
    sha256 = "175716e1cc8448283d6ba9fcb7abf75321c636d4c919c1cc4c34927a085d2017"
    url = "https://github.com/staticfloat/libtapi_jll.jl/releases/download/v1300.6.1-GCCBootstrap-x86_64-linux-gnu/libtapi-extract_log-v1300.6.1-x86_64-linux-gnu.tar.gz"
