[[libtapi]]
arch = "x86_64"
git-tree-sha1 = "9b08fd4d96507b1abc4b2045282aa5fbce9ad847"
libc = "glibc"
os = "linux"

    [[libtapi.download]]
    sha256 = "90ff0cea9f02a049fa1babb484df0c41b2de0577522427f2bbc5575151db4206"
    url = "https://github.com/staticfloat/libtapi_jll.jl/releases/download/v1300.6.1-GCCBootstrap-x86_64-linux-gnu/libtapi-v1300.6.1-x86_64-linux-gnu.tar.gz"

[[libtapi-build_log]]
arch = "x86_64"
git-tree-sha1 = "6e8dd21c9a0b6ad23002ea02a67796270f15ffe3"
lazy = true
libc = "glibc"
os = "linux"

    [[libtapi-build_log.download]]
    sha256 = "d58325b9388b261915d46c291dad07d799458fad757cb3980560b24f3cdc51c7"
    url = "https://github.com/staticfloat/libtapi_jll.jl/releases/download/v1300.6.1-GCCBootstrap-x86_64-linux-gnu/libtapi-build_log-v1300.6.1-x86_64-linux-gnu.tar.gz"

[[libtapi-extract_log]]
arch = "x86_64"
git-tree-sha1 = "bc429ba9ebdf9da41c9a05d848eae8f569ab815f"
lazy = true
libc = "glibc"
os = "linux"

    [[libtapi-extract_log.download]]
    sha256 = "3058fa6b78e0e80b32532b843a4287616914d2332d81f60ca5f25383d1dcea72"
    url = "https://github.com/staticfloat/libtapi_jll.jl/releases/download/v1300.6.1-GCCBootstrap-x86_64-linux-gnu/libtapi-extract_log-v1300.6.1-x86_64-linux-gnu.tar.gz"
