[[libtapi]]
arch = "aarch64"
git-tree-sha1 = "8fb8c971e838e70ab9e319e18ddef38f06da0785"
libc = "glibc"
os = "linux"

    [[libtapi.download]]
    sha256 = "1538516938ccb902d8354456c3fba39751aef657c2ad2f8aaa569e3747cb9ca2"
    url = "https://github.com/staticfloat/libtapi_jll.jl/releases/download/v1300.6.1-bb2/GCCBootstrap-x86_64-linux-gnu/libtapi-v1300.6.1-aarch64-linux-gnu.tar.gz"
[[libtapi]]
arch = "x86_64"
git-tree-sha1 = "9b08fd4d96507b1abc4b2045282aa5fbce9ad847"
libc = "glibc"
os = "linux"

    [[libtapi.download]]
    sha256 = "bc4c4738bb20578c279be1c3f2927c0cb5e3ebb1c453b55a89632b132400e0ef"
    url = "https://github.com/staticfloat/libtapi_jll.jl/releases/download/v1300.6.1-bb2/GCCBootstrap-x86_64-linux-gnu/libtapi-v1300.6.1-x86_64-linux-gnu.tar.gz"

[[libtapi-build_log]]
arch = "aarch64"
git-tree-sha1 = "758274bb6bdc7e533d609d93a00ec2760f90fcff"
lazy = true
libc = "glibc"
os = "linux"

    [[libtapi-build_log.download]]
    sha256 = "d3b4cf25f2b113db519f2d126e4a08f95eba19d6b5ddfe5ca4003b18b31eaf65"
    url = "https://github.com/staticfloat/libtapi_jll.jl/releases/download/v1300.6.1-bb2/GCCBootstrap-x86_64-linux-gnu/libtapi-build_log-v1300.6.1-aarch64-linux-gnu.tar.gz"
[[libtapi-build_log]]
arch = "x86_64"
git-tree-sha1 = "386c8a6de14a7f56e5069d15480769c7843cb45a"
lazy = true
libc = "glibc"
os = "linux"

    [[libtapi-build_log.download]]
    sha256 = "6a812d0308a03a823463a5554ff1785a568c4581ef732aa2bfe44d5beef6ab8d"
    url = "https://github.com/staticfloat/libtapi_jll.jl/releases/download/v1300.6.1-bb2/GCCBootstrap-x86_64-linux-gnu/libtapi-build_log-v1300.6.1-x86_64-linux-gnu.tar.gz"

[[libtapi-extract_log]]
arch = "aarch64"
git-tree-sha1 = "aa8188801e72a7aaf72c2e48d15a0093e930dc89"
lazy = true
libc = "glibc"
os = "linux"

    [[libtapi-extract_log.download]]
    sha256 = "8fc253289c735b478ab69002633673637508c5db23d81a93564ff42f9a375c3a"
    url = "https://github.com/staticfloat/libtapi_jll.jl/releases/download/v1300.6.1-bb2/GCCBootstrap-x86_64-linux-gnu/libtapi-extract_log-v1300.6.1-aarch64-linux-gnu.tar.gz"
[[libtapi-extract_log]]
arch = "x86_64"
git-tree-sha1 = "537276bc6e7a50f1bfc07c13be19ba29db388677"
lazy = true
libc = "glibc"
os = "linux"

    [[libtapi-extract_log.download]]
    sha256 = "5cedd47b6ac793fc480a8b140f66605038c0a94e9198b041b351ea3930dc6e56"
    url = "https://github.com/staticfloat/libtapi_jll.jl/releases/download/v1300.6.1-bb2/GCCBootstrap-x86_64-linux-gnu/libtapi-extract_log-v1300.6.1-x86_64-linux-gnu.tar.gz"
